export const UserDetailsActions = {
    UPDATE_USER_DETAIL: 'USER_DETAIL_UPDATE',
    CLEAR_USER_DETAIL: 'USER_DETAIL_CLEAR',
    CHANGE_AVATAR_USER_DETAIL: 'USER_DETAIL_CHANGE_AVATAR',
    LOAD_USER_DETAIL: 'USER_DETAIL_CHANGE_AVATAR',
}